arch: "amd64"

ingress:
  enabled: true
  hosts:
    - sage.devprod-evergreen.staging.corp.mongodb.com
service:
  targetPort: 8080
mesh:
  enabled: true

services:
  - name: http
    ingress: true
    port: 80
    probes: true
    protocol: TCP
    targetPort: 8080
    type: ClusterIP

resources:
  requests:
    cpu: 4
    memory: 8Gi
  limits:
    cpu: 8
    memory: 8Gi

env:
  EVERGREEN_API_USER: sage
  EVERGREEN_API_URL: https://evergreen.mongodb.com/rest/v2
  EVERGREEN_URL: https://evergreen.mongodb.com
  EVERGREEN_GRAPHQL_ENDPOINT: https://evergreen.mongodb.com/mcp/graphql/query
  PORT: 8080
  OTEL_COLLECTOR_URL: http://otel-collector-web-app.devprod-platform.svc.cluster.local:4318/v1/traces
  OTEL_LOG_COLLECTOR_URL: http://otel-collector-web-app.devprod-platform.svc.cluster.local:4318/v1/logs
  HONEYCOMB_TEAM: sage
  NODE_ENV: staging
  DB_NAME: sage
  OTEL_EXPORTER_OTLP_ENDPOINT: https://api.braintrust.dev/otel
  SENTRY_DSN: https://3db76f0989faad4c102a8708fba9446f@o4504991346720768.ingest.us.sentry.io/4509905876942849


envSecrets:
  AZURE_OPENAI_API_KEY: parsley-ai-secrets
  AZURE_OPENAI_ENDPOINT: parsley-ai-secrets
  EVERGREEN_API_KEY: parsley-ai-secrets
  MONGODB_URI: parsley-ai-secrets
  OTEL_EXPORTER_OTLP_HEADERS: parsley-ai-secrets
  BRAINTRUST_API_KEY: parsley-ai-secrets
  HONEYCOMB_API_KEY: parsley-ai-secrets

serviceAccount:
  enabled: true
  serviceEntitlementRequests:
   - name: sage-web-app-to-devprod-platform-otel-collector-web-app
     serviceCatalogEntryRef:
       name: otel-collector-web-app
       namespace: devprod-platform
     requestedPaths:
     - methods:
       - POST
       paths:
       - /v1/logs
       - /v1/traces
       - /v1/logs
       - /opentelemetry.proto.collector.trace.v1.TraceService/Export
       - /opentelemetry.proto.collector.logs.v1.LogsService/Export
       - /opentelemetry.proto.collector.metrics.v1.MetricsService/Export
